sudo: false
language: node_js
node_js:
    - "6"
before_script:
    - npm install
    - "export PATH=$(pwd)/node_modules/.bin:$PATH"
script: 
    - karma start --single-run
    #- istanbul cover jasmine-node --captureExceptions wordmapper/client/test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
