sudo: false
language: node_js
node_js:
    - "6"
before_script:
    - npm install
    - "export PATH=$(pwd)/node_modules/.bin:$PATH"
script: 
    - karma start --single-run
    - if [ -f ./coverage/report-lcov/lcov.info ]; then cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage; fi