sudo: false
language: node_js
node_js:
    - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
    - npm install
    - "export PATH=$(pwd)/node_modules/.bin:$PATH"
script: 
    - istanbul cover --root wordmapper/server --include-all-sources jasmine JASMINE_CONFIG_PATH=jasmine.server.json
    - LCOV_INFO=./coverage/lcov.info; if [ -e $LCOV_INFO ] && [ -s $LCOV_INFO ]; then cat $LCOV_INFO | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage; fi
    - karma start --single-run
    - LCOV_INFO=./coverage/report-lcov/lcov.info; if [ -e $LCOV_INFO ] && [ -s $LCOV_INFO ]; then cat $LCOV_INFO | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage; fi
