DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS user_admin CASCADE;
DROP TABLE IF EXISTS page CASCADE;
DROP TABLE IF EXISTS source CASCADE;
DROP TABLE IF EXISTS page_source CASCADE;
DROP TABLE IF EXISTS alignment CASCADE;
DROP TABLE IF EXISTS word CASCADE;
